# -*- coding: utf-8 -*-
"""ai_img_generate_single.ipynb

Automatically generated by Colaboratory.


!pip install huggingface_hub --upgrade

!pip install --upgrade diffusers transformers accelerate safetensors omegaconf invisible-watermark>=0.2.0

!pip install requests

!pip install googletrans==4.0.0-rc1

!pip install boto3
"""


import requests
import pandas as pd
import os
from googletrans import Translator
import logging
import boto3
from botocore.exceptions import ClientError
import os
from io import BytesIO
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import random

from diffusers import StableDiffusionXLPipeline, StableDiffusionXLImg2ImgPipeline, AutoPipelineForText2Image, DiffusionPipeline 
import torch
from PIL import Image
from pathlib import Path


AWS_ACCESS_KEY_ID = 'access_key_id'
AWS_SECRET_ACCESS_KEY = 'secret_access_key'
S3_BUCKET_NAME = 'opendatahub.ai-generated-images'
AWS_REGION = 'eu-west-1'

s3_client = boto3.client('s3', aws_access_key_id=AWS_ACCESS_KEY_ID, aws_secret_access_key=AWS_SECRET_ACCESS_KEY)

pipe = DiffusionPipeline.from_pretrained(
            "stabilityai/stable-diffusion-xl-base-1.0"
            , torch_dtype       = torch.float16
            , use_safetensors   = True
            , variant           = "fp16"
            , custom_pipeline   = "lpw_stable_diffusion_xl",
        ).to("cuda")

def save_images_with_ids_to_s3(images, df):
    for index, row in df.iterrows():
        item_id = row['Id']
        image = images[index]  # Assuming each images_array corresponds to a single image

        filename = f"{item_id}.png"
        key = f"images/{filename}"

        # Convert image to bytes
        with BytesIO() as image_bytes:
            image.save(image_bytes, format='PNG')
            image_bytes.seek(0)

            # Upload image to S3
            s3_client.upload_fileobj(image_bytes, S3_BUCKET_NAME, key)
            print(f"Uploaded {key} to S3 bucket.")


def save_images_mobility(path, images, df):
    for index, row in df.iterrows():
        item_id = row[0]
        filename = f"{item_id}.png"  # Nome del file basato sull'ID
        images[index].save(os.path.join(path, filename))

def api_get(url):
    headers = {}
    response = requests.get(url, headers=headers)
    return response.json()


def process_dataframe(api_url):
  if 'mobility' in api_url:
        allItems = api_get(api_url)
        dfAllItems = pd.DataFrame.from_records(allItems)

  else:
        all_items= api_get(api_url)
        dfAllItems = pd.DataFrame.from_dict(all_items, orient='index').transpose()
  def extract_specific_columns_and_details(df):

      if 'EventShort' in api_url:
         columns_to_keep = ['Id', 'EventTitle', 'EventDescriptionEN']

      elif 'Article' in api_url:
         columns_to_keep = ['Id', 'Type', 'Detail', 'AdditionalArticleInfos']

      elif 'Event' in api_url:
         columns_to_keep = ['Id', 'Type', 'Detail']

      elif 'Weather' in api_url:
        columns_to_keep = ['Id', 'evolution', 'Conditions', 'Mountain']

      elif 'Accommodation' in api_url:
         columns_to_keep = ['Id', 'AccoDetail', 'AccoType', 'AccoCategoryId']

      elif 'Venue' in api_url:
        columns_to_keep = ['Id', 'Detail']

      elif 'ActivityPoi' in api_url:
        columns_to_keep =['Id', 'Detail', 'PoiType', 'SubType']

      elif 'WebcamInfo' in api_url:
        columns_to_keep = ['Id', 'Detail', 'Shortname']

      elif 'Region' in api_url:
        columns_to_keep = ['Id', 'Detail']

      elif 'Municipality' in api_url:
        columns_to_keep = ['Id', 'Detail']

      elif 'District' in api_url:
        columns_to_keep = ['Id', 'Detail']

      elif 'SkiRegion' in api_url:
        columns_to_keep = ['Id', 'Detail']

      elif 'TourismAssociation' in api_url:
         columns_to_keep = ['Id', 'Detail']

      elif 'SkiArea' in api_url:
        columns_to_keep = ['Id', 'Detail']

      elif 'WineAward' in api_url:
         columns_to_keep = ['Id', 'Detail']

      elif 'mobility' in api_url:
        columns_to_keep = ['id']

      columns_to_drop = [col for col in df.columns if col not in columns_to_keep]
      df = df.drop(columns=columns_to_drop)
      return df

  def detail_translate(item):
      if 'Detail' in item:
            languages = item['Detail']
            translator = Translator()
            language_priority = ['en', 'de', 'it']  # Define language priority

            english_detail = None
            translated_detail = None

            for lang in language_priority:
                if lang in languages:
                    detail_info = item['Detail'][lang]
                    if lang == 'en':
                        english_detail = detail_info
                    else:
                        translator = Translator()

                        # Translate non-English text fields within 'Detail' dictionary
                        translated_detail = {}
                        for field, value in detail_info.items():
                            if value and isinstance(value, str):  # Translate if value is non-empty string
                                try:
                                    translated = translator.translate(value, src=lang, dest='en')
                                    translated_detail[field] = translated.text
                                except Exception as e:
                                    print(f"Translation error: {e}")

            # Return English detail if available, otherwise return translated detail, or None if neither is available
            return english_detail or translated_detail

      return None


  def extract_translate_detail_common(item):
      if 'Detail' in item:
          detail_info = item['Detail']
          for lang, info in detail_info.items():
              if lang == 'en':
                  return info  # Return the 'en' section from 'Detail'

      return None


  def addinfo_translate(item):
      if 'AdditionalArticleInfos' in item:
          languages = item['AdditionalArticleInfos']
          language_priority = ['en', 'de', 'it']  # Define language priority

          english_addinfo = None
          translated_addinfo = None

          for lang in language_priority:
              if lang in languages:
                  detail_info = item['AdditionalArticleInfos'][lang]
                  if lang == 'en':
                      english_addinfo = detail_info
                  else:
                      translator = Translator()

                      # Translate non-English text fields within 'Detail' dictionary
                      translated_addinfo = {}
                      for field, value in detail_info.items():
                          if value and isinstance(value, str):  # Translate if value is non-empty string
                              translated = translator.translate(value, src=lang, dest='en')
                              translated_addinfo[field] = translated.text

          # Return English detail if available, otherwise return translated detail, or None if neither is available
          return english_addinfo or translated_addinfo

      return None

  def extract_translate_acco(item):
      if 'AccoDetail' in item:
          accodetail_info = item['AccoDetail']
          if 'en' in accodetail_info:
              return accodetail_info['en']  # Return the 'en' section from 'AccoDetail'

      return None

  def acco_manager(df):
      df = extract_specific_columns_and_details(df)

      df['AccoDetail'] = df.apply(extract_translate_acco, axis=1)
      return df

  def article_manager(df):
      df = extract_specific_columns_and_details(df)
      df['Detail'] = df.apply(detail_translate, axis=1)
      df['AdditionalArticleInfos'] = df.apply(addinfo_translate, axis=1)
      df
      return df

  def event_manager(df):
      df = extract_specific_columns_and_details(df)
      df['Detail'] = df.apply(detail_translate, axis=1)

      return df

  def venue_manager(df):
      df = extract_specific_columns_and_details(df)
      df['Detail'] = df.apply(detail_translate, axis=1)

      return df

  def activity_manager(df):
      df = extract_specific_columns_and_details(df)
      df['Detail'] = df.apply(detail_translate, axis=1)

      return df

  def eventShort_manager(df):
      df = extract_specific_columns_and_details(df)

      return df

  def webcamInfo_manager(df):
      df = extract_specific_columns_and_details(df)
      return df

  def region_manager(df):
      df = extract_specific_columns_and_details(df)
      df['Detail'] = df.apply(detail_translate, axis=1)
      return df

  def municipality_manager(df):
      df = extract_specific_columns_and_details(df)
      df['Detail'] = df.apply(detail_translate, axis=1)
      return df

  def district_manager(df):
      df = extract_specific_columns_and_details(df)
      df['Detail'] = df.apply(detail_translate, axis=1)
      return df

  def skiRegion_manager(df):
      df = extract_specific_columns_and_details(df)
      df['Detail'] = df.apply(detail_translate, axis=1)
      return df

  def tourismAssociation_manager(df):
      df = extract_specific_columns_and_details(df)
      df['Detail'] = df.apply(detail_translate, axis=1)
      return df

  def skiArea_manager(df):
      df = extract_specific_columns_and_details(df)
      df['Detail'] = df.apply(detail_translate, axis=1)
      return df

  def wineAward_manager(df):
      df = extract_specific_columns_and_details(df)
      df['Detail'] = df.apply(detail_translate, axis=1)
      return df

  def weather_manager(df):
      df = extract_specific_columns_and_details(df)
      return df

  def mobility_manager(df):
      df = extract_specific_columns_and_details(df)
      return df

  prompt_1 = "no text, no faces, drawing, colorful "
  if 'Article' in api_url:
    df = article_manager(dfAllItems)
  elif 'EventShort' in api_url:
    df = eventShort_manager(dfAllItems)
    prompt_1 = 'event, events, ' + prompt_1
  elif 'Event' in api_url:
    prompt_1 = 'event, events, ' + prompt_1
    df= event_manager(dfAllItems)
  elif 'Weather' in api_url:
    prompt_1 = 'weather, ' + prompt_1
    df= weather_manager(dfAllItems)
  elif 'Accommodation' in api_url:
    prompt_1 = 'accommodation, ' + prompt_1
    df = acco_manager(dfAllItems)
  elif 'Venue' in api_url:
    prompt_1 = 'venue, ' + prompt_1
    df = venue_manager(dfAllItems)
  elif 'ActivityPoi' in api_url:
    prompt_1 = 'activity, POI, PointOfInterest ' + prompt_1
    df = activity_manager(dfAllItems)
  elif 'WebcamInfo' in api_url:
    prompt_1 = 'Webcam, location, landscape, ' + prompt_1
    df = webcamInfo_manager(dfAllItems)
  elif 'Region' in api_url:
    prompt_1 = 'region, city, ' + prompt_1
    df = region_manager(dfAllItems)
  elif 'Municipality' in api_url:
    prompt_1 = 'municipality, city, ' + prompt_1
    df = municipality_manager(dfAllItems)
  elif 'District' in api_url:
    prompt_1 = 'district, city, ' + prompt_1
    df = district_manager(dfAllItems)
  elif 'SkiRegion' in api_url:
    df = skiRegion_manager(dfAllItems)
  elif 'TourismAssociation' in api_url:
    prompt_1 = 'tourism, tourismassociation, ' + prompt_1
    df = tourismAssociation_manager(dfAllItems)
  elif 'SkiArea' in api_url:
    df = skiArea_manager(dfAllItems)
  elif 'WineAward' in api_url:
    prompt_1 = 'wine, wineaward, ' + prompt_1
    df = wineAward_manager(dfAllItems)
  elif 'mobility' in api_url:
    prompt_1 = 'timeseries, data, '
    df = mobility_manager(dfAllItems)

  seed = random.randint(0, 1000)
  num_images_per_prompt = 1
  generator = torch.Generator(device='cuda').manual_seed(seed)
  images = []

  for index, row in df.iterrows():
        prompt = prompt_1 + str(row)
        print(prompt)
        generated_images = pipe(prompt=prompt, num_images_per_prompt=num_images_per_prompt, generator=generator).images

        if generated_images:  # Aggiungi le immagini generate solo se non è vuoto
            images.extend(generated_images)
        if not os.path.isdir("img"):

          os.makedirs("img")

    #saving images in folder with the Item's id
  save_images_with_ids_to_s3(images, df.head(15))

  return df